### ISSUE TITLE
Error processing some image files (App13 segments)

### ISSUE THREAD

**Issue by d6y** [d6y/telepost#1]
```
[info] Running Main ......
[error] org.apache.sanselan.ImageReadException: Jpeg contains more than one Photoshop App13 segment.
[error]     at org.apache.sanselan.formats.jpeg.JpegImageParser.getPhotoshopMetadata(JpegImageParser.java:609)
[error]     at org.apache.sanselan.formats.jpeg.JpegImageParser.getMetadata(JpegImageParser.java:309)
[error]     at org.apache.sanselan.Sanselan.getMetadata(Sanselan.java:978)
[error]     at org.apache.sanselan.Sanselan.getMetadata(Sanselan.java:871)
[error]     at org.apache.sanselan.Sanselan.getMetadata(Sanselan.java:846)
[error]     at com.dallaway.telegram.email.ImageResizer$.scale(ImageResize.scala:52)
[error]     at com.dallaway.telegram.email.EmailWriter$class.com$dallaway$telegram$email$EmailWriter$$savedAttachment(EmailWriter.scala:113)
[error]     at com.dallaway.telegram.email.EmailWriter$$anonfun$attachments$3.apply(EmailWriter.scala:75)
[error]     at com.dallaway.telegram.email.EmailWriter$$anonfun$attachments$3.apply(EmailWriter.scala:72)
[error]     at scala.collection.TraversableLike$WithFilter$$anonfun$flatMap$2.apply(TraversableLike.scala:759)
[error]     at scala.collection.Iterator$class.foreach(Iterator.scala:742)
[error]     at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
[error]     at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
[error]     at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error]     at scala.collection.TraversableLike$WithFilter.flatMap(TraversableLike.scala:758)
[error]     at com.dallaway.telegram.email.EmailWriter$class.attachments(EmailWriter.scala:72)
[error]     at com.dallaway.telegram.email.EmailWriter$class.write(EmailWriter.scala:30)
[error]     at Main$.write(Main.scala:6)
[error]     at Main$$anonfun$2.apply(Main.scala:18)
[error]     at Main$$anonfun$2.apply(Main.scala:18)
[error]     at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
[error]     at Main$$anonfun$4.apply(Main.scala:23)
[error]     at Main$$anonfun$4.apply(Main.scala:23)
[error]     at com.dallaway.telegram.email.Imap$$anonfun$checkMail$1$$anonfun$apply$1.apply$mcVI$sp(Imap.scala:40)
[error]     at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:166)
[error]     at com.dallaway.telegram.email.Imap$$anonfun$checkMail$1.apply(Imap.scala:37)
[error]     at com.dallaway.telegram.email.Imap$$anonfun$checkMail$1.apply(Imap.scala:32)
[error]     at com.dallaway.telegram.email.Imap$class.withInbox$1(Imap.scala:23)
[error]     at com.dallaway.telegram.email.Imap$class.checkMail(Imap.scala:32)
[error]     at Main$.checkMail(Main.scala:6)
[error]     at Main$.delayedEndpoint$Main$1(Main.scala:23)
[error]     at Main$delayedInit$body.apply(Main.scala:6)
[error]     at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
[error]     at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
[error]     at scala.App$$anonfun$main$1.apply(App.scala:76)
[error]     at scala.App$$anonfun$main$1.apply(App.scala:76)
[error]     at scala.collection.immutable.List.foreach(List.scala:381)
[error]     at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
[error]     at scala.App$class.main(App.scala:76)
[error]     at Main$.main(Main.scala:6)
[error]     at Main.main(Main.scala)
[success] Total time: 18 s, completed 02-Oct-2016 18:53:32
```

**Comment by d6y** [comment]
The image is being fetched via IMAP, but here it is:

![img_3101](https://cloud.githubusercontent.com/assets/102661/19022697/0fbb96b6-88d6-11e6-872d-c34d878fe88d.JPG)

**Comment by d6y** [comment]
Re: https://issues.apache.org/jira/browse/IMAGING-100

**Comment by d6y** [comment]
Another example:

![img_9855](https://cloud.githubusercontent.com/assets/102661/19218656/9a46543a-8df7-11e6-9343-3f519541d83b.JPG)

**Comment by d6y** [comment]
IImageMagick (e.g., `convert -thumbnail 500`) handles these images.

[SO 5905868](http://stackoverflow.com/questions/5905868/how-to-rotate-jpeg-images-based-on-the-orientation-metadata#6010475) leads me to [metadata-extractor](https://github.com/drewnoakes/metadata-extractor) and [thumbnailator](https://github.com/coobird/thumbnailator) as worth investigating.
